event_inherited();
bulletSpd = 20;
bulletcounter = 0;
bulletinterval = 10;
bulletspreadcounter = 0;
guns = -1;
invincible = false;
_id = id;
exhaustcounter = 0;
image_index = 0;
image_speed = 0;
